In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('nigeria-rent.csv')
df

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets
0,Newly Built 4 Bedroom Semi Detached House With Bq,4 BEDROOM HOUSE FOR RENT,"White Oak Estate, Ologolo Opp. Agungi, Ologolo...","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets
1,Superb 4 Bedroom Semi Detached Duplex With Bq,4 BEDROOM HOUSE FOR RENT,"Hrc Estate Beside Vgc Estate, Vgc Lekki Lagos","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets
2,Furnished 2 Bedroom Terrace Duplex For Rent !!!,2 BEDROOM HOUSE FOR RENT,Osapa London Lekki Lagos,"3,500,000",1,0,0,2 beds,3 baths,3 Toilets
3,2 Bedroom Apartment For Rent,2 BEDROOM HOUSE FOR RENT,Ologolo Lekki Lagos,"2,700,000",1,1,0,2 beds,3 baths,3 Toilets
4,?? Brand New 2 Bedroom Flat For Rent!!! (groun...,2 BEDROOM HOUSE FOR RENT,Mojisola Onikoyi Ikoyi Lagos,"5,000,000",1,1,0,2 beds,3 baths,3 Toilets
...,...,...,...,...,...,...,...,...,...,...
98075,4 Bedroom Duplex In Serene Neighborhood,4 BEDROOM HOUSE FOR RENT,Akala Akobo Ibadan Oyo,"900,000",0,0,0,4 beds,4 baths,4 Toilets
98076,Lovely Built 3 Bedroom Flats Self Compound,3 BEDROOM SELF CONTAIN FOR RENT,Oluwaga Road. Baruwa Ipaja Lagos,"500,000",0,1,1,3 beds,4 baths,4 Toilets
98077,Executive 2 Bedroom Flat,2 BEDROOM BLOCKS OF FLATS FOR RENT,By Sterling Bank Magboro Obafemi Owode Ogun,"330,000",0,0,1,2 beds,3 baths,3 Toilets
98078,Executive Brand New 2 Bedroom Flat All Rooms E...,2 BEDROOM BLOCKS OF FLATS FOR RENT,Arepo Arepo Arepo Ogun,"400,000",0,1,1,2 beds,3 baths,3 Toilets
98079,3 Bedroom Flat All Ensuit,3 BEDROOM BLOCKS OF FLATS FOR RENT,"3bedroom Flat At Jeje Area, Apete.all Rooms En...","150,000",0,0,0,3 beds,3 baths,3 Toilets

In [3]:
# Retrieving houses in Lagos and Abuja states only.

#since the last word in an adress is the state, we apply split() on last word in location column as follows 

df1 = df.copy()
df1['split'] = df1['Location'].apply(lambda x: x.split()[-1])


df1 = df1[(df1["split"] == 'Abuja') | (df1["split"] == 'Lagos')]
df1

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets,split
0,Newly Built 4 Bedroom Semi Detached House With Bq,4 BEDROOM HOUSE FOR RENT,"White Oak Estate, Ologolo Opp. Agungi, Ologolo...","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets,Lagos
1,Superb 4 Bedroom Semi Detached Duplex With Bq,4 BEDROOM HOUSE FOR RENT,"Hrc Estate Beside Vgc Estate, Vgc Lekki Lagos","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets,Lagos
2,Furnished 2 Bedroom Terrace Duplex For Rent !!!,2 BEDROOM HOUSE FOR RENT,Osapa London Lekki Lagos,"3,500,000",1,0,0,2 beds,3 baths,3 Toilets,Lagos
3,2 Bedroom Apartment For Rent,2 BEDROOM HOUSE FOR RENT,Ologolo Lekki Lagos,"2,700,000",1,1,0,2 beds,3 baths,3 Toilets,Lagos
4,?? Brand New 2 Bedroom Flat For Rent!!! (groun...,2 BEDROOM HOUSE FOR RENT,Mojisola Onikoyi Ikoyi Lagos,"5,000,000",1,1,0,2 beds,3 baths,3 Toilets,Lagos
...,...,...,...,...,...,...,...,...,...,...,...
98071,A Newly Renovated 3 Bedrooms Flat With 2b & 3t,3 BEDROOM SHARED APARTMENT FOR RENT,"No.3, Alice Ogunsona Stt, Hilltop Estate, Off ...","300,000",0,0,0,3 beds,2 baths,3 Toilets,Lagos
98072,Lovely 2 Bedroom Flat,2 BEDROOM PENTHOUSE FOR RENT,Behind Romay Garden Ilasan Lekki Lagos,"1,200,000",0,0,0,2 beds,3 baths,3 Toilets,Lagos
98073,Comfortably Built 5 Bedroom Terrace Duplex,5 BEDROOM TERRACED DUPLEX HOUSE FOR RENT,Ikate Area Lekki Lagos,"4,500,000",0,1,1,5 beds,6 baths,6 Toilets,Lagos
98074,Executive Standard Mini Flat,1 BEDROOM MINI FLAT FOR RENT,Onipetesi Estate Mangoro Ikeja Lagos,"400,000",0,0,0,1 beds,1 baths,1 Toilets,Lagos
98076,Lovely Built 3 Bedroom Flats Self Compound,3 BEDROOM SELF CONTAIN FOR RENT,Oluwaga Road. Baruwa Ipaja Lagos,"500,000",0,1,1,3 beds,4 baths,4 Toilets,Lagos

In [4]:
df2 = df1.copy()

In [5]:
df2.Price.unique()

array(['5,000,000/year', '3,500,000', '2,700,000', ..., '1,470,000',
       '475,000', '710,000'], dtype=object)

In [6]:
df2["Title"] = df2["Title"].apply(str.lower)
df2

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets,split
0,newly built 4 bedroom semi detached house with bq,4 BEDROOM HOUSE FOR RENT,"White Oak Estate, Ologolo Opp. Agungi, Ologolo...","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets,Lagos
1,superb 4 bedroom semi detached duplex with bq,4 BEDROOM HOUSE FOR RENT,"Hrc Estate Beside Vgc Estate, Vgc Lekki Lagos","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets,Lagos
2,furnished 2 bedroom terrace duplex for rent !!!,2 BEDROOM HOUSE FOR RENT,Osapa London Lekki Lagos,"3,500,000",1,0,0,2 beds,3 baths,3 Toilets,Lagos
3,2 bedroom apartment for rent,2 BEDROOM HOUSE FOR RENT,Ologolo Lekki Lagos,"2,700,000",1,1,0,2 beds,3 baths,3 Toilets,Lagos
4,?? brand new 2 bedroom flat for rent!!! (groun...,2 BEDROOM HOUSE FOR RENT,Mojisola Onikoyi Ikoyi Lagos,"5,000,000",1,1,0,2 beds,3 baths,3 Toilets,Lagos
...,...,...,...,...,...,...,...,...,...,...,...
98071,a newly renovated 3 bedrooms flat with 2b & 3t,3 BEDROOM SHARED APARTMENT FOR RENT,"No.3, Alice Ogunsona Stt, Hilltop Estate, Off ...","300,000",0,0,0,3 beds,2 baths,3 Toilets,Lagos
98072,lovely 2 bedroom flat,2 BEDROOM PENTHOUSE FOR RENT,Behind Romay Garden Ilasan Lekki Lagos,"1,200,000",0,0,0,2 beds,3 baths,3 Toilets,Lagos
98073,comfortably built 5 bedroom terrace duplex,5 BEDROOM TERRACED DUPLEX HOUSE FOR RENT,Ikate Area Lekki Lagos,"4,500,000",0,1,1,5 beds,6 baths,6 Toilets,Lagos
98074,executive standard mini flat,1 BEDROOM MINI FLAT FOR RENT,Onipetesi Estate Mangoro Ikeja Lagos,"400,000",0,0,0,1 beds,1 baths,1 Toilets,Lagos
98076,lovely built 3 bedroom flats self compound,3 BEDROOM SELF CONTAIN FOR RENT,Oluwaga Road. Baruwa Ipaja Lagos,"500,000",0,1,1,3 beds,4 baths,4 Toilets,Lagos

In [7]:
#retrieving homes with a certain home type and removing commmercial properties
home_type = ['bungalow','duplex','terrace duplex','semi detached duplex','mansion','flat','apartment','detached duplex']
df3 = df2[df2["Title"].str.contains('|'.join(home_type))]
df3=df3[~df3['More Info'].str.contains('COMMERCIAL')]
df3

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets,split
1,superb 4 bedroom semi detached duplex with bq,4 BEDROOM HOUSE FOR RENT,"Hrc Estate Beside Vgc Estate, Vgc Lekki Lagos","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets,Lagos
2,furnished 2 bedroom terrace duplex for rent !!!,2 BEDROOM HOUSE FOR RENT,Osapa London Lekki Lagos,"3,500,000",1,0,0,2 beds,3 baths,3 Toilets,Lagos
3,2 bedroom apartment for rent,2 BEDROOM HOUSE FOR RENT,Ologolo Lekki Lagos,"2,700,000",1,1,0,2 beds,3 baths,3 Toilets,Lagos
4,?? brand new 2 bedroom flat for rent!!! (groun...,2 BEDROOM HOUSE FOR RENT,Mojisola Onikoyi Ikoyi Lagos,"5,000,000",1,1,0,2 beds,3 baths,3 Toilets,Lagos
5,4 bedroom terrace duplex for rent,4 BEDROOM HOUSE FOR RENT,Chevron Lekki Lagos,"4,000,000",1,0,0,4 beds,5 baths,5 Toilets,Lagos
...,...,...,...,...,...,...,...,...,...,...,...
98071,a newly renovated 3 bedrooms flat with 2b & 3t,3 BEDROOM SHARED APARTMENT FOR RENT,"No.3, Alice Ogunsona Stt, Hilltop Estate, Off ...","300,000",0,0,0,3 beds,2 baths,3 Toilets,Lagos
98072,lovely 2 bedroom flat,2 BEDROOM PENTHOUSE FOR RENT,Behind Romay Garden Ilasan Lekki Lagos,"1,200,000",0,0,0,2 beds,3 baths,3 Toilets,Lagos
98073,comfortably built 5 bedroom terrace duplex,5 BEDROOM TERRACED DUPLEX HOUSE FOR RENT,Ikate Area Lekki Lagos,"4,500,000",0,1,1,5 beds,6 baths,6 Toilets,Lagos
98074,executive standard mini flat,1 BEDROOM MINI FLAT FOR RENT,Onipetesi Estate Mangoro Ikeja Lagos,"400,000",0,0,0,1 beds,1 baths,1 Toilets,Lagos
98076,lovely built 3 bedroom flats self compound,3 BEDROOM SELF CONTAIN FOR RENT,Oluwaga Road. Baruwa Ipaja Lagos,"500,000",0,1,1,3 beds,4 baths,4 Toilets,Lagos

In [8]:
#Flats and apartments are the same. Below code changes occurence of 'apartment' to flat for easier categorisation

df3['type'] = df3['Title'].apply(lambda x: 'flat' if 'apartment' in x else x)

In [9]:
#arranging home types into 'Home' column
df3['Home'] = df3['type'].apply(lambda x: 'SEMI DETACHED DUPLEX' if 'semi detached duplex' in x else x)

for home in ['terrace duplex','detached duplex','mansion','duplex','bungalow','flat']:

    df3['Home'] = df3['Home'].apply(lambda x: f'{home}'.upper() if home in x else x)
 
df3

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets,split,type,Home
1,superb 4 bedroom semi detached duplex with bq,4 BEDROOM HOUSE FOR RENT,"Hrc Estate Beside Vgc Estate, Vgc Lekki Lagos","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets,Lagos,superb 4 bedroom semi detached duplex with bq,SEMI DETACHED DUPLEX
2,furnished 2 bedroom terrace duplex for rent !!!,2 BEDROOM HOUSE FOR RENT,Osapa London Lekki Lagos,"3,500,000",1,0,0,2 beds,3 baths,3 Toilets,Lagos,furnished 2 bedroom terrace duplex for rent !!!,TERRACE DUPLEX
3,2 bedroom apartment for rent,2 BEDROOM HOUSE FOR RENT,Ologolo Lekki Lagos,"2,700,000",1,1,0,2 beds,3 baths,3 Toilets,Lagos,flat,FLAT
4,?? brand new 2 bedroom flat for rent!!! (groun...,2 BEDROOM HOUSE FOR RENT,Mojisola Onikoyi Ikoyi Lagos,"5,000,000",1,1,0,2 beds,3 baths,3 Toilets,Lagos,?? brand new 2 bedroom flat for rent!!! (groun...,FLAT
5,4 bedroom terrace duplex for rent,4 BEDROOM HOUSE FOR RENT,Chevron Lekki Lagos,"4,000,000",1,0,0,4 beds,5 baths,5 Toilets,Lagos,4 bedroom terrace duplex for rent,TERRACE DUPLEX
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98071,a newly renovated 3 bedrooms flat with 2b & 3t,3 BEDROOM SHARED APARTMENT FOR RENT,"No.3, Alice Ogunsona Stt, Hilltop Estate, Off ...","300,000",0,0,0,3 beds,2 baths,3 Toilets,Lagos,a newly renovated 3 bedrooms flat with 2b & 3t,FLAT
98072,lovely 2 bedroom flat,2 BEDROOM PENTHOUSE FOR RENT,Behind Romay Garden Ilasan Lekki Lagos,"1,200,000",0,0,0,2 beds,3 baths,3 Toilets,Lagos,lovely 2 bedroom flat,FLAT
98073,comfortably built 5 bedroom terrace duplex,5 BEDROOM TERRACED DUPLEX HOUSE FOR RENT,Ikate Area Lekki Lagos,"4,500,000",0,1,1,5 beds,6 baths,6 Toilets,Lagos,comfortably built 5 bedroom terrace duplex,TERRACE DUPLEX
98074,executive standard mini flat,1 BEDROOM MINI FLAT FOR RENT,Onipetesi Estate Mangoro Ikeja Lagos,"400,000",0,0,0,1 beds,1 baths,1 Toilets,Lagos,executive standard mini flat,FLAT
98076,lovely built 3 bedroom flats self compound,3 BEDROOM SELF CONTAIN FOR RENT,Oluwaga Road. Baruwa Ipaja Lagos,"500,000",0,1,1,3 beds,4 baths,4 Toilets,Lagos,lovely built 3 bedroom flats self compound,FLAT

In [10]:
#making dummy variables for Abuja and Lagos states
df3['Abuja'] = df3['split'].apply(lambda x: int('Abuja' in x))

In [11]:
#removing unnecesary data
df4 = df3.copy()
index1 = df4[(df4['Bedrooms']==' beds') | (df4['Bedrooms'] == '0 beds')].index


df4 = df4.drop(index1)
index2 =  df4[(df4['Toilets']==' Toilets') | (df4['Toilets'] == '0 Toilets')].index

df4 = df4.drop(index2)
index3 = df4[(df4['Bathrooms']==' baths') | (df4['Bathrooms'] == '0 baths')].index

df4 = df4.drop(index3)

In [12]:
#changing bedrooms, bathrooms and toilets to int type
rooms = ['Bedrooms','Bathrooms','Toilets']

for room in rooms:
     df4[f'{room}'] = df4[f'{room}'].apply(lambda x: int(x[0]))
    

# Turning price column to int type
df4['Price'] = df4['Price'].apply(lambda x: int(x.split('/')[0].replace(',','')))

In [13]:
#filtering price extremes

df4 = df4[(df4['Price']<1700000000000) & (df4['Price']>100000)]

index1 = df4[(df4['Price']<=100000) & (df4['Bedrooms']>=3)].index
df4 = df4.drop(index1)
index2 = df4[(df4['Abuja'] == 0) &(df4['Price']==2.500000e+10)].index
df4 = df4.drop(index2)

In [14]:
df5 = df4.copy()
df5 = df5.drop(96310)

In [15]:
df6=df5.copy()
df6['Zones'] = df6['Location'].apply(lambda x: 'Lagos_high' if 'Ikoyi' in x else x)

for location in ['Lekki','Victoria Island', 'Magodo', 'Ikeja', 'Surulere', 'Maryland']:
    df6['Zones'] = df6['Zones'].apply(lambda x: 'Lagos_high' if location in x else x)
    
for location in ['Badagry','Ogba','Mushin','Agege','Festac', 'Ikorodu','Yaba','Igando','Apapa','Ojo','Ipaja','Bariga']:
    df6['Zones'] = df6['Zones'].apply(lambda x: 'Lagos_low' if location in x else x)
    
for location in ['Asokoro','Maitama','Katampe','Garki','Wuse']:
    df6['Zones'] = df6['Zones'].apply(lambda x: 'Abuja_high' if location in x else x)
    
for location in ['Kubwa','Lugbe','Kuje','Dawaki','Jikwoyi','Nyanya','Mpape','Gwagwalada']:
    df6['Zones'] = df6['Zones'].apply(lambda x: 'Abuja_low' if location in x else x)

index3 = df6[~df6['Zones'].str.contains('|'.join(['Lagos_low','Lagos_high','Abuja_high','Abuja_low']))].index

for i in index3:
    if df6.loc[i,'split'] == 'Lagos':
        df6.loc[i,'Zones'] = 'Lagos_mid'
    
    elif df6.loc[i,'split'] == 'Abuja':
        df6.loc[i,'Zones'] = 'Abuja_mid'

In [16]:
df6

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets,split,type,Home,Abuja,Zones
1,superb 4 bedroom semi detached duplex with bq,4 BEDROOM HOUSE FOR RENT,"Hrc Estate Beside Vgc Estate, Vgc Lekki Lagos",5000000,0,1,0,4,4,5,Lagos,superb 4 bedroom semi detached duplex with bq,SEMI DETACHED DUPLEX,0,Lagos_high
2,furnished 2 bedroom terrace duplex for rent !!!,2 BEDROOM HOUSE FOR RENT,Osapa London Lekki Lagos,3500000,1,0,0,2,3,3,Lagos,furnished 2 bedroom terrace duplex for rent !!!,TERRACE DUPLEX,0,Lagos_high
3,2 bedroom apartment for rent,2 BEDROOM HOUSE FOR RENT,Ologolo Lekki Lagos,2700000,1,1,0,2,3,3,Lagos,flat,FLAT,0,Lagos_high
4,?? brand new 2 bedroom flat for rent!!! (groun...,2 BEDROOM HOUSE FOR RENT,Mojisola Onikoyi Ikoyi Lagos,5000000,1,1,0,2,3,3,Lagos,?? brand new 2 bedroom flat for rent!!! (groun...,FLAT,0,Lagos_high
5,4 bedroom terrace duplex for rent,4 BEDROOM HOUSE FOR RENT,Chevron Lekki Lagos,4000000,1,0,0,4,5,5,Lagos,4 bedroom terrace duplex for rent,TERRACE DUPLEX,0,Lagos_high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98071,a newly renovated 3 bedrooms flat with 2b & 3t,3 BEDROOM SHARED APARTMENT FOR RENT,"No.3, Alice Ogunsona Stt, Hilltop Estate, Off ...",300000,0,0,0,3,2,3,Lagos,a newly renovated 3 bedrooms flat with 2b & 3t,FLAT,0,Lagos_low
98072,lovely 2 bedroom flat,2 BEDROOM PENTHOUSE FOR RENT,Behind Romay Garden Ilasan Lekki Lagos,1200000,0,0,0,2,3,3,Lagos,lovely 2 bedroom flat,FLAT,0,Lagos_high
98073,comfortably built 5 bedroom terrace duplex,5 BEDROOM TERRACED DUPLEX HOUSE FOR RENT,Ikate Area Lekki Lagos,4500000,0,1,1,5,6,6,Lagos,comfortably built 5 bedroom terrace duplex,TERRACE DUPLEX,0,Lagos_high
98074,executive standard mini flat,1 BEDROOM MINI FLAT FOR RENT,Onipetesi Estate Mangoro Ikeja Lagos,400000,0,0,0,1,1,1,Lagos,executive standard mini flat,FLAT,0,Lagos_high
98076,lovely built 3 bedroom flats self compound,3 BEDROOM SELF CONTAIN FOR RENT,Oluwaga Road. Baruwa Ipaja Lagos,500000,0,1,1,3,4,4,Lagos,lovely built 3 bedroom flats self compound,FLAT,0,Lagos_low

In [45]:
#  finding correlated variables which can cause errors in the model

df8 = df6.drop("Price", axis=1)
data_corr = df8.corr()
data_corr

C:\Users\Skipps\AppData\Local\Temp\ipykernel_21308\802113820.py:5: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data_corr = df8.corr()

,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets,Abuja
Serviced,1.000000,0.130504,0.114319,0.103245,0.102386,0.147802,0.101365
Newly Built,0.130504,1.000000,0.113415,0.025959,0.070074,0.093327,0.064942
Furnished,0.114319,0.113415,1.000000,-0.048446,0.019558,-0.024825,-0.034660
Bedrooms,0.103245,0.025959,-0.048446,1.000000,0.921696,0.908113,0.103115
Bathrooms,0.102386,0.070074,0.019558,0.921696,1.000000,0.918970,0.138694
Toilets,0.147802,0.093327,-0.024825,0.908113,0.918970,1.000000,0.118658
Abuja,0.101365,0.064942,-0.034660,0.103115,0.138694,0.118658,1.000000

In [78]:
# dropping unnecessary features from the table (including the highly correlated features) and making dummy variables

df9 = pd.get_dummies(df6, columns = ['Home','Zones'], drop_first = True)
df9 = df9.drop(["Bathrooms", "Toilets",'Title', 'More Info','Location','split','type','Abuja'], axis=1)


# data to be used in training the models
y = df9.values[:,0:1]
x_2 = df9.values[:,1:]

In [79]:
# splitting x (i.e x_2)  and y into training, test and validation sets

x_2_train, x_2_test_validation, y_train, y_test_validation = train_test_split(x_2, y, random_state = 2, test_size = 0.3)
x_2_test, x_validation, y_test, y_validation = train_test_split(x_2_test_validation, y_test_validation, test_size = 0.5)

In [99]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error as mse
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform as sp_randfloat
from scipy.stats import randint as sp_randint
import tensorflow as tf

In [100]:
from sklearn.ensemble import RandomForestRegressor

In [82]:
#  machine learning model training


#training a neural network model



model_deep2 = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 32, input_shape = (15,), activation = 'relu'),
    tf.keras.layers.Dense(units = 32, activation = 'relu'),
    tf.keras.layers.Dense(units = 32, activation = 'relu'),
    tf.keras.layers.Dense(units = 1, activation = tf.keras.activations.linear)
])

early_stop = tf.keras.callbacks.EarlyStopping(patience = 10, monitor = 'val_loss', mode='min', verbose = 1)

model_deep2.compile(optimizer = 'Adam', loss = 'mean_squared_error')

In [83]:
hist2 = model_deep2.fit(x_2_train, y_train, batch_size=32, epochs = 2000, validation_data = (x_validation,y_validation), verbose = 2, callbacks = [early_stop] )

Epoch 1/2000
1191/1191 - 3s - loss: 12461379457908736.0000 - val_loss: 14618971311439872.0000 - 3s/epoch - 3ms/step
Epoch 2/2000
1191/1191 - 1s - loss: 12457548347080704.0000 - val_loss: 14609111140270080.0000 - 1s/epoch - 1ms/step
Epoch 3/2000
1191/1191 - 1s - loss: 12444381051092992.0000 - val_loss: 14584627679199232.0000 - 1s/epoch - 1ms/step
Epoch 4/2000
1191/1191 - 1s - loss: 12425102016643072.0000 - val_loss: 14558986724442112.0000 - 1s/epoch - 1ms/step
Epoch 5/2000
1191/1191 - 1s - loss: 12410969426755584.0000 - val_loss: 14541909934473216.0000 - 1s/epoch - 1ms/step
Epoch 6/2000
1191/1191 - 1s - loss: 12403572419330048.0000 - val_loss: 14531857563516928.0000 - 1s/epoch - 1ms/step
Epoch 7/2000
1191/1191 - 1s - loss: 12399814322946048.0000 - val_loss: 14526151699464192.0000 - 1s/epoch - 1ms/step
Epoch 8/2000
1191/1191 - 1s - loss: 12398151096860672.0000 - val_loss: 14522985234825216.0000 - 1s/epoch - 1ms/step
Epoch 9/2000
1191/1191 - 1s - loss: 12397315725721600.0000 - val_loss: 14521091154247680.0000 - 1s/epoch - 1ms/step
Epoch 10/2000
1191/1191 - 1s - loss: 12396799255904256.0000 - val_loss: 14519726428389376.0000 - 1s/epoch - 1ms/step
Epoch 11/2000
1191/1191 - 1s - loss: 12396406266396672.0000 - val_loss: 14519017758785536.0000 - 1s/epoch - 1ms/step
Epoch 12/2000
1191/1191 - 1s - loss: 12396103471202304.0000 - val_loss: 14518006293987328.0000 - 1s/epoch - 1ms/step
Epoch 13/2000
1191/1191 - 1s - loss: 12395853289357312.0000 - val_loss: 14517502709071872.0000 - 1s/epoch - 1ms/step
Epoch 14/2000
1191/1191 - 1s - loss: 12395569821515776.0000 - val_loss: 14517203135102976.0000 - 1s/epoch - 1ms/step
Epoch 15/2000
1191/1191 - 1s - loss: 12395315344703488.0000 - val_loss: 14516532046462976.0000 - 1s/epoch - 1ms/step
Epoch 16/2000
1191/1191 - 1s - loss: 12395084490211328.0000 - val_loss: 14516107918442496.0000 - 1s/epoch - 1ms/step
Epoch 17/2000
1191/1191 - 1s - loss: 12394874036813824.0000 - val_loss: 14515576416239616.0000 - 1s/epoch - 1ms/step
Epoch 18/2000
1191/1191 - 1s - loss: 12394664657158144.0000 - val_loss: 14515485148184576.0000 - 1s/epoch - 1ms/step
Epoch 19/2000
1191/1191 - 1s - loss: 12394386558025728.0000 - val_loss: 14515577489981440.0000 - 1s/epoch - 1ms/step
Epoch 20/2000
1191/1191 - 1s - loss: 12394280257585152.0000 - val_loss: 14515302612074496.0000 - 1s/epoch - 1ms/step
Epoch 21/2000
1191/1191 - 1s - loss: 12394066582962176.0000 - val_loss: 14514951498498048.0000 - 1s/epoch - 1ms/step
Epoch 22/2000
1191/1191 - 1s - loss: 12393898005495808.0000 - val_loss: 14514194510512128.0000 - 1s/epoch - 1ms/step
Epoch 23/2000
1191/1191 - 1s - loss: 12393712248160256.0000 - val_loss: 14513956139827200.0000 - 1s/epoch - 1ms/step
Epoch 24/2000
1191/1191 - 1s - loss: 12393593062817792.0000 - val_loss: 14514074251427840.0000 - 1s/epoch - 1ms/step
Epoch 25/2000
1191/1191 - 1s - loss: 12393501794762752.0000 - val_loss: 14513383835435008.0000 - 1s/epoch - 1ms/step
Epoch 26/2000
1191/1191 - 1s - loss: 12393328922329088.0000 - val_loss: 14513047754244096.0000 - 1s/epoch - 1ms/step
Epoch 27/2000
1191/1191 - 1s - loss: 12393144238735360.0000 - val_loss: 14512892061679616.0000 - 1s/epoch - 1ms/step
Epoch 28/2000
1191/1191 - 1s - loss: 12393079814225920.0000 - val_loss: 14512943601287168.0000 - 1s/epoch - 1ms/step
Epoch 29/2000
1191/1191 - 1s - loss: 12392958481399808.0000 - val_loss: 14512677313314816.0000 - 1s/epoch - 1ms/step
Epoch 30/2000
1191/1191 - 1s - loss: 12392816747479040.0000 - val_loss: 14512416394051584.0000 - 1s/epoch - 1ms/step
Epoch 31/2000
1191/1191 - 1s - loss: 12392756617936896.0000 - val_loss: 14512028773253120.0000 - 1s/epoch - 1ms/step
Epoch 32/2000
1191/1191 - 1s - loss: 12392625621434368.0000 - val_loss: 14511748526637056.0000 - 1s/epoch - 1ms/step
Epoch 33/2000
1191/1191 - 1s - loss: 12392486034997248.0000 - val_loss: 14511550958141440.0000 - 1s/epoch - 1ms/step
Epoch 34/2000
1191/1191 - 1s - loss: 12392422684229632.0000 - val_loss: 14511395265576960.0000 - 1s/epoch - 1ms/step
Epoch 35/2000
1191/1191 - 1s - loss: 12392313162563584.0000 - val_loss: 14511475796213760.0000 - 1s/epoch - 1ms/step
Epoch 36/2000
1191/1191 - 1s - loss: 12392227263217664.0000 - val_loss: 14511255679139840.0000 - 1s/epoch - 1ms/step
Epoch 37/2000
1191/1191 - 1s - loss: 12392139216388096.0000 - val_loss: 14511021603422208.0000 - 1s/epoch - 1ms/step
Epoch 38/2000
1191/1191 - 1s - loss: 12392100561682432.0000 - val_loss: 14510638277591040.0000 - 1s/epoch - 1ms/step
Epoch 39/2000
1191/1191 - 1s - loss: 12391971712663552.0000 - val_loss: 14510694112165888.0000 - 1s/epoch - 1ms/step
Epoch 40/2000
1191/1191 - 1s - loss: 12391890108284928.0000 - val_loss: 14510752094224384.0000 - 1s/epoch - 1ms/step
Epoch 41/2000
1191/1191 - 1s - loss: 12391858969772032.0000 - val_loss: 14510525534699520.0000 - 1s/epoch - 1ms/step
Epoch 42/2000
1191/1191 - 1s - loss: 12391776291651584.0000 - val_loss: 14510524460957696.0000 - 1s/epoch - 1ms/step
Epoch 43/2000
1191/1191 - 1s - loss: 12391714014625792.0000 - val_loss: 14510413865549824.0000 - 1s/epoch - 1ms/step
Epoch 44/2000
1191/1191 - 1s - loss: 12391658180050944.0000 - val_loss: 14510351588524032.0000 - 1s/epoch - 1ms/step
Epoch 45/2000
1191/1191 - 1s - loss: 12391587313090560.0000 - val_loss: 14510101406679040.0000 - 1s/epoch - 1ms/step
Epoch 46/2000
1191/1191 - 1s - loss: 12391577649414144.0000 - val_loss: 14509572051959808.0000 - 1s/epoch - 1ms/step
Epoch 47/2000
1191/1191 - 1s - loss: 12391465980264448.0000 - val_loss: 14509729892007936.0000 - 1s/epoch - 1ms/step
Epoch 48/2000
1191/1191 - 1s - loss: 12391438062977024.0000 - val_loss: 14509730965749760.0000 - 1s/epoch - 1ms/step
Epoch 49/2000
1191/1191 - 1s - loss: 12391385449627648.0000 - val_loss: 14509822233804800.0000 - 1s/epoch - 1ms/step
Epoch 50/2000
1191/1191 - 1s - loss: 12391323172601856.0000 - val_loss: 14509926386761728.0000 - 1s/epoch - 1ms/step
Epoch 51/2000
1191/1191 - 1s - loss: 12391352163631104.0000 - val_loss: 14509857667284992.0000 - 1s/epoch - 1ms/step
Epoch 52/2000
1191/1191 - 1s - loss: 12391297402798080.0000 - val_loss: 14509435686748160.0000 - 1s/epoch - 1ms/step
Epoch 53/2000
1191/1191 - 1s - loss: 12391238346997760.0000 - val_loss: 14509455014100992.0000 - 1s/epoch - 1ms/step
Epoch 54/2000
1191/1191 - 1s - loss: 12391203987259392.0000 - val_loss: 14509071688269824.0000 - 1s/epoch - 1ms/step
Epoch 55/2000
1191/1191 - 1s - loss: 12391214724677632.0000 - val_loss: 14509208053481472.0000 - 1s/epoch - 1ms/step
Epoch 56/2000
1191/1191 - 1s - loss: 12391229757063168.0000 - val_loss: 14509255298121728.0000 - 1s/epoch - 1ms/step
Epoch 57/2000
1191/1191 - 1s - loss: 12391088023142400.0000 - val_loss: 14509302542761984.0000 - 1s/epoch - 1ms/step
Epoch 58/2000
1191/1191 - 1s - loss: 12391084801916928.0000 - val_loss: 14509114637942784.0000 - 1s/epoch - 1ms/step
Epoch 59/2000
1191/1191 - 1s - loss: 12391060105854976.0000 - val_loss: 14509004042534912.0000 - 1s/epoch - 1ms/step
Epoch 60/2000
1191/1191 - 1s - loss: 12391023598632960.0000 - val_loss: 14508921364414464.0000 - 1s/epoch - 996us/step
Epoch 61/2000
1191/1191 - 1s - loss: 12391020377407488.0000 - val_loss: 14508702321082368.0000 - 1s/epoch - 998us/step
Epoch 62/2000
1191/1191 - 1s - loss: 12391004271280128.0000 - val_loss: 14509350861144064.0000 - 1s/epoch - 1ms/step
Epoch 63/2000
1191/1191 - 1s - loss: 12390964542832640.0000 - val_loss: 14508618569220096.0000 - 1s/epoch - 1ms/step
Epoch 64/2000
1191/1191 - 1s - loss: 12390946289221632.0000 - val_loss: 14508630380380160.0000 - 1s/epoch - 1ms/step
Epoch 65/2000
1191/1191 - 1s - loss: 12390897970839552.0000 - val_loss: 14508844055003136.0000 - 1s/epoch - 1ms/step
Epoch 66/2000
1191/1191 - 1s - loss: 12390941994254336.0000 - val_loss: 14508827948875776.0000 - 1s/epoch - 1ms/step
Epoch 67/2000
1191/1191 - 1s - loss: 12390896897097728.0000 - val_loss: 14508702321082368.0000 - 1s/epoch - 1ms/step
Epoch 68/2000
1191/1191 - 1s - loss: 12390816366460928.0000 - val_loss: 14508767819333632.0000 - 1s/epoch - 1ms/step
Epoch 69/2000
1191/1191 - 1s - loss: 12390857168650240.0000 - val_loss: 14508754934431744.0000 - 1s/epoch - 1ms/step
Epoch 70/2000
1191/1191 - 1s - loss: 12390847504973824.0000 - val_loss: 14508468245364736.0000 - 1s/epoch - 1ms/step
Epoch 71/2000

1191/1191 - 1s - loss: 12390791670398976.0000 - val_loss: 14508162228944896.0000 - 1s/epoch - 1ms/step
Epoch 72/2000
1191/1191 - 1s - loss: 12390773416787968.0000 - val_loss: 14508235243388928.0000 - 1s/epoch - 1ms/step
Epoch 73/2000
1191/1191 - 1s - loss: 12390748720726016.0000 - val_loss: 14508092435726336.0000 - 1s/epoch - 1ms/step
Epoch 74/2000
1191/1191 - 1s - loss: 12390744425758720.0000 - val_loss: 14508183703781376.0000 - 1s/epoch - 1ms/step
Epoch 75/2000
1191/1191 - 1s - loss: 12390722950922240.0000 - val_loss: 14507963586707456.0000 - 1s/epoch - 1ms/step
Epoch 76/2000
1191/1191 - 1s - loss: 12390678927507456.0000 - val_loss: 14507968955416576.0000 - 1s/epoch - 1ms/step
Epoch 77/2000
1191/1191 - 1s - loss: 12390750868209664.0000 - val_loss: 14507886277296128.0000 - 1s/epoch - 1ms/step
Epoch 78/2000
1191/1191 - 1s - loss: 12390672485056512.0000 - val_loss: 14507866949943296.0000 - 1s/epoch - 1ms/step
Epoch 79/2000
1191/1191 - 1s - loss: 12390623092932608.0000 - val_loss: 14507731658473472.0000 - 1s/epoch - 1ms/step
Epoch 80/2000
1191/1191 - 1s - loss: 12390616650481664.0000 - val_loss: 14507916342067200.0000 - 1s/epoch - 1ms/step
Epoch 81/2000
1191/1191 - 1s - loss: 12390584438226944.0000 - val_loss: 14508128942948352.0000 - 1s/epoch - 1ms/step
Epoch 82/2000
1191/1191 - 1s - loss: 12390600544354304.0000 - val_loss: 14508045191086080.0000 - 1s/epoch - 1ms/step
Epoch 83/2000
1191/1191 - 1s - loss: 12390605913063424.0000 - val_loss: 14508074182115328.0000 - 1s/epoch - 1ms/step
Epoch 84/2000
1191/1191 - 1s - loss: 12390547931004928.0000 - val_loss: 14508330806411264.0000 - 1s/epoch - 1ms/step
Epoch 85/2000
1191/1191 - 1s - loss: 12390544709779456.0000 - val_loss: 14508209473585152.0000 - 1s/epoch - 1ms/step
Epoch 86/2000
1191/1191 - 1s - loss: 12390566184615936.0000 - val_loss: 14507953923031040.0000 - 1s/epoch - 1ms/step
Epoch 87/2000
1191/1191 - 1s - loss: 12390535046103040.0000 - val_loss: 14507714478604288.0000 - 1s/epoch - 1ms/step
Epoch 88/2000
1191/1191 - 1s - loss: 12390509276299264.0000 - val_loss: 14507694077509632.0000 - 1s/epoch - 1ms/step
Epoch 89/2000
1191/1191 - 1s - loss: 12390508202557440.0000 - val_loss: 14507971102900224.0000 - 1s/epoch - 1ms/step
Epoch 90/2000
1191/1191 - 1s - loss: 12390487801462784.0000 - val_loss: 14507892719747072.0000 - 1s/epoch - 1ms/step
Epoch 91/2000
1191/1191 - 1s - loss: 12390481359011840.0000 - val_loss: 14507695151251456.0000 - 1s/epoch - 1ms/step
Epoch 92/2000
1191/1191 - 1s - loss: 12390488875204608.0000 - val_loss: 14508132164173824.0000 - 1s/epoch - 1ms/step
Epoch 93/2000
1191/1191 - 1s - loss: 12390443778048000.0000 - val_loss: 14507715552346112.0000 - 1s/epoch - 1ms/step
Epoch 94/2000
1191/1191 - 1s - loss: 12390421229469696.0000 - val_loss: 14508031232442368.0000 - 1s/epoch - 1ms/step
Epoch 95/2000
1191/1191 - 1s - loss: 12390572627066880.0000 - val_loss: 14508014052573184.0000 - 1s/epoch - 1ms/step
Epoch 96/2000
1191/1191 - 1s - loss: 12390431966887936.0000 - val_loss: 14507914194583552.0000 - 1s/epoch - 1ms/step
Epoch 97/2000
1191/1191 - 1s - loss: 12390407270825984.0000 - val_loss: 14507938890645504.0000 - 1s/epoch - 1ms/step
Epoch 98/2000
1191/1191 - 1s - loss: 12390463105400832.0000 - val_loss: 14507616768098304.0000 - 1s/epoch - 1ms/step
Epoch 99/2000
1191/1191 - 1s - loss: 12390412639535104.0000 - val_loss: 14507609251905536.0000 - 1s/epoch - 1ms/step
Epoch 100/2000
1191/1191 - 1s - loss: 12390364321153024.0000 - val_loss: 14507656496545792.0000 - 1s/epoch - 1ms/step
Epoch 101/2000
1191/1191 - 1s - loss: 12390357878702080.0000 - val_loss: 14507670455189504.0000 - 1s/epoch - 1ms/step
Epoch 102/2000
1191/1191 - 1s - loss: 12390326740189184.0000 - val_loss: 14507272096972800.0000 - 1s/epoch - 1ms/step
Epoch 103/2000
1191/1191 - 1s - loss: 12390346067542016.0000 - val_loss: 14507297866776576.0000 - 1s/epoch - 1ms/step
Epoch 104/2000
1191/1191 - 1s - loss: 12390336403865600.0000 - val_loss: 14506966080552960.0000 - 1s/epoch - 1ms/step
Epoch 105/2000
1191/1191 - 1s - loss: 12390382574764032.0000 - val_loss: 14507055201124352.0000 - 1s/epoch - 1ms/step
Epoch 106/2000
1191/1191 - 1s - loss: 12390309560320000.0000 - val_loss: 14506952121909248.0000 - 1s/epoch - 1ms/step
Epoch 107/2000
1191/1191 - 1s - loss: 12390306339094528.0000 - val_loss: 14506957490618368.0000 - 1s/epoch - 1ms/step
Epoch 108/2000
1191/1191 - 1s - loss: 12390262315679744.0000 - val_loss: 14507150764146688.0000 - 1s/epoch - 1ms/step
Epoch 109/2000
1191/1191 - 1s - loss: 12390266610647040.0000 - val_loss: 14507386987347968.0000 - 1s/epoch - 1ms/step
Epoch 110/2000
1191/1191 - 1s - loss: 12390248357036032.0000 - val_loss: 14507698372476928.0000 - 1s/epoch - 1ms/step
Epoch 111/2000
1191/1191 - 1s - loss: 12390255873228800.0000 - val_loss: 14507580260876288.0000 - 1s/epoch - 1ms/step
Epoch 112/2000
1191/1191 - 1s - loss: 12390261241937920.0000 - val_loss: 14507641464160256.0000 - 1s/epoch - 1ms/step
Epoch 113/2000
1191/1191 - 1s - loss: 12390252652003328.0000 - val_loss: 14507436379471872.0000 - 1s/epoch - 1ms/step
Epoch 114/2000
1191/1191 - 1s - loss: 12390224734715904.0000 - val_loss: 14507432084504576.0000 - 1s/epoch - 1ms/step
Epoch 115/2000
1191/1191 - 1s - loss: 12390218292264960.0000 - val_loss: 14507191566336000.0000 - 1s/epoch - 1ms/step
Epoch 116/2000
1191/1191 - 1s - loss: 12390204333621248.0000 - val_loss: 14507347258900480.0000 - 1s/epoch - 1ms/step
Epoch 116: early stopping

In [101]:
mse(model_deep2.predict(x_2_test),y_test, squared=False)

256/256 [==============================] - 0s 724us/step

111400668.729245

In [102]:
y_train_flat = y_train.ravel()

In [103]:
gbr_2 = GradientBoostingRegressor(n_estimators=250).fit(x_2_train, y_train_flat)
mse(gbr_2.predict(x_2_train), y_train_flat, squared=False), mse(gbr_2.predict(x_validation), y_validation, squared=False)

(111077957.58222803, 120514470.72089949)

In [104]:
rfr = RandomForestRegressor(max_depth=10).fit(x_2_train, y_train_flat)
mse(rfr.predict(x_2_train), y_train_flat, squared=False), mse(rfr.predict(x_validation), y_validation, squared=False)

(110480278.44257413, 121366258.81962529)

In [105]:
knn = KNeighborsRegressor(n_neighbors=10).fit(x_2_train, y_train_flat)
mse(knn.predict(x_2_train), y_train_flat, squared=False), mse(knn.predict(x_validation), y_validation, squared=False)

(121264893.43053237, 131364469.34957953)

In [106]:
# optimising the parameters for gbr model

model = GradientBoostingRegressor()
parameters = {'learning_rate':sp_randfloat(),
               'subsample' : sp_randfloat(),
                'n_estimators': sp_randint(100,1000),
                 'max_depth': sp_randint(4,10)
             }
randm = RandomizedSearchCV(estimator=model,param_distributions = parameters, cv =5, n_iter=10, n_jobs=1)

randm.fit(x_2_train,y_train_flat)

RandomizedSearchCV(cv=5, estimator=GradientBoostingRegressor(), n_jobs=1,
                   param_distributions={'learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x00000143EB9658D0>,
                                        'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000014403AA2020>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001440854D390>,
                                        'subsample': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x0000014403AA34F0>})

In [107]:
randm.best_score_

-0.01345001692472827

In [108]:
randm.best_params_

{'learning_rate': 0.013110996115827223,
 'max_depth': 9,
 'n_estimators': 572,
 'subsample': 0.8073586015007739}

In [109]:
gbr2_new = GradientBoostingRegressor(n_estimators=572, max_depth = 9, learning_rate = 0.013110996115827223, subsample = 0.8073586015007739).fit(x_2_train, y_train_flat)
mse(gbr_2.predict(x_2_train), y_train_flat, squared=False), mse(gbr_2.predict(x_validation), y_validation, squared=False)

(111077957.58222803, 120514470.72089949)

In [111]:
#exporting gbr model which will be used in the main website
import pickle
with open('gbr2_new','wb') as f:
    pickle.dump(gbr2_new,f)